In [1]:
import pandas as pd
df = pd.read_excel("https://github.com/development0694/employee_data_analysis/raw/refs/heads/main/employee_records.xlsx")
df.head()

   emp_id   name   age  department   salary  experience     city
0  3727.0  Kiran  29.0     Finance  36781.0        15.0   Mumbai
1  3006.0  Priya  33.0     Finance  33336.0         4.0   Mumbai
2  4176.0  Rahul  39.0  Operations  63231.0        26.0   Mumbai
3   231.0  Rohit   NaN          HR  90752.0        18.0   Mumbai
4  2332.0  Rohit  52.0   Marketing  56306.0        24.0  Chennai

In [2]:
#displaying last 10  records
print("Last 10 records : ")
df.tail(10)

Last 10 records :

      emp_id   name   age department   salary  experience       city
5010  1530.0  Sneha  24.0  Marketing      NaN        23.0      Delhi
5011  4340.0  Rohit   NaN    Finance  83020.0        32.0      Delhi
5012  2676.0  Kiran  50.0         IT  86799.0        23.0    Kolkata
5013   674.0  Priya  23.0         IT  41757.0        35.0      Delhi
5014  1485.0  Sneha  59.0         IT  67125.0        34.0      Delhi
5015  4401.0  Pooja  39.0    Finance      NaN        13.0  Bangalore
5016  1026.0  Sneha   NaN      Sales      NaN         4.0     Mumbai
5017  3214.0   Neha   NaN    Finance  66901.0        15.0    Kolkata
5018  1479.0  Pooja  56.0         IT      NaN        32.0    Kolkata
5019  3925.0  Kiran  30.0  Marketing  50060.0        27.0       Pune